name: DungeonMaze
main: com.timvisee.dungeonmaze.DungeonMaze
version: 0.1.8
load: STARTUP
depend: [Essentials]
commands:
  dm:
    description: Dungeon Maze command
    usage: /dm
  dungeonmaze:
    description: Dungeon Maze command
    usage: /dungeonmaze